swagger: "2.0"
info:
  title: "DeepSpace Docs"
  description: >
    Docs de DeepSpace API.
  version: "1.0.0"
host: "${DB_HOST}:${PORT}"
schemes:
  - "http"
tags:
  - name: "users"
    description: "Todo lo relacionado a users"
  - name: "chats"
    description: "Todo lo relacionado a chats"
  - name: "messages"
    description: "Todo lo relacionado a messages"

paths:
  /users:
    get:
      tags: ["users", ]
      summary: "List all users"
      description: "Fetches all users from the database."
      responses:
        200:
          description: "A list of users."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    post:
      tags: ["users", ]
      summary: "Create a new user"
      description: "Creates a new user with the provided data."
      parameters:
        - in: "body"
          name: "body"
          description: "User object that needs to be added to the database."
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "User created successfully."
          schema:
            $ref: "#/definitions/User"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /chats:
    get:
      tags: ["chats", ]
      summary: "Recupera los chats de un usuario"
      parameters:
      - in: "query"
        name: "userId"
        required: true
        description: "ID del usuario"
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Una lista de chats"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Chat"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    post:
      tags: ["chats", ]
      summary: "Crea un nuevo chat"
      description: "Crea un nuevo chat con los datos proporcionados."
      parameters:
        - in: "body"
          name: "body"
          description: "El chat que debe ser creado"
          required: true
          schema:
            $ref: "#/definitions/ChatEntity"
  /chats/{id}:
    get:
      tags: ["chats"]
      summary: "Recupera los mensajes de un chat"
      parameters:
        - in: "path"
          name: "id"
          required: true
          description: "ID del chat"
          type: "integer"
          format: "int64"
      responses:
        404:
          description: "No se encontraró el chat"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Una lista de mensajes de un chat"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/FullMessage"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /messages:
    post:
      tags: ["messages", ]
      summary: "Crea un mensaje nuevo"
      description: "Crea un mensaje nuevo con los datos proporcionados."
      parameters:
        - in: "body"
          name: "body"
          description: "El mensaje que debe ser creado"
          required: true
          schema:
            $ref: "#/definitions/MessageEntity"
      responses:
        400:
          description: "Faltaron parametros. Se requiere idUser, idChat y message o files"
          schema:
            $ref: '#/definitions/Error'
        403:
          description: "No tienes permiso para enviar mensajes en este chat"
          schema:
            $ref: '#/definitions/Error'
        201:
          description: "Mensaje creado correctamente."
          schema:
            $ref: "#/definitions/FullMessage"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    delete:
      tags: ["messages", ]
      summary: "Elimina un mensaje"
      description: "Elimina un mensaje con el id proporcionado."
      parameters:
        - in: "query"
          name: "id"
          required: true
          description: "ID del mensaje"
          type: "integer"
          format: "int64"
      responses:
        404:
          description: "No se encontró el mensaje"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Mensaje eliminado correctamente."
          schema:
            $ref: "#/definitions/Success"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    patch:
      tags: ["messages", ]
      summary: "Edita un mensaje"
      description: "Edita un mensaje con el id proporcionado."
      parameters:
        - in: "query"
          name: "id"
          required: true
          description: "ID del mensaje"
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "El mensaje que debe ser editado"
          required: true
          schema:
            $ref: "#/definitions/MessageUpdateEntity"
      responses:
        404:
          description: "No se encontró el mensaje"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Mensaje editado correctamente."
          schema:
            $ref: "#/definitions/FullMessage"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'

responses:
  500:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: "object"
    properties:
      error:
        type: "string"
  Success:
    type: "object"
    properties:
      message:
        type: "string"
  Chat:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      imageUrl:
        type: "string"
        nullable: true
      canSendMessage:
        type: "boolean"
      lastMessage:
        $ref: "#/definitions/Message"
      isDm: 
        type: "boolean"
  ChatEntity:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      image_url:
        type: "string"
        nullable: true
      mode:
        type: "string"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      lastName:
        type: "string"
      profilePictureUrl:
        type: "string"
  FullMessage:
    type: "object"
    properties:
      id:
        type: "integer"
      idChat: 
        type: "integer"
      idUser:
        type: "integer"
      message:
        type: "string"
      lastEditDate: 
        type: "string"
        nullable: true
        format: "date-time"
      deletesAt: 
        type: "string"
        nullable: true
        format: "date-time"
      forwaded:
        type: "boolean"
      respondingTo:
        type: "integer"
        nullable: true
      time:
        type: "string"
        format: "date-time"
      user:
        $ref: "#/definitions/User"
      files:
        type: "array"
        items:
          $ref: "#/definitions/MessageFile"
  Message:
    type: "object"
    properties:
      message:
        type: "string"
      time:
        type: "string"
        format: "date-time"
  MessageEntity:
    type: "object"
    properties:
      idChat:
        type: "integer"
      idUser:
        type: "integer"
      message:
        type: "string"
      pinned:
        type: "boolean"
        default: false
      deletesAt:
        type: "string"
        format: "date-time"
        nullable: true
      forwaded:
        type: "boolean"
      respondingTo:
        type: "integer"
        nullable: true
      files:
        type: "array"
        items:
          $ref: "#/definitions/File"
  MessageFile:
    type: "object"
    properties:
      id:
        type: "integer"
      file_url:
        type: "string"
  definitions:
    File: # TODO revisar este modelo, es el que se usa para pasar archivos de front a back
      type: "object"
      properties:
        file:
          type: "string"
          format: "binary"
          description: "File to be uploaded"
  MessageUpdateEntity:
    type: "object"
    properties:
      message:
        type: "string"
      pinned:
        type: "boolean"
        default: false
      deletesAt:
        type: "string"
        format: "date-time"
        nullable: true
