swagger: "2.0"
info:
  title: "DeepSpace Docs"
  description: >
    Docs for DeepSpace API.
  version: "1.0.0"
host: "${DB_HOST}:${PORT}"
schemes:
  - "http"
tags:
  - name: "users"
    description: "Operations about users"
  - name: "chats"
    description: "Operations about chats"
  - name: "messages"
    description: "Operations about messages"

paths:
  /users:
    get:
      tags: ["users", ]
      summary: "List all users"
      description: "Fetches all users from the database."
      responses:
        200:
          description: "A list of users."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    post:
      tags: ["users", ]
      summary: "Create a new user"
      description: "Creates a new user with the provided data."
      parameters:
        - in: "body"
          name: "body"
          description: "User object that needs to be added to the database."
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "User created successfully."
          schema:
            $ref: "#/definitions/User"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /chats:
    get:
      tags: ["chats", ]
      summary: "List all chats"
  /messages:
    get:
      tags: ["messages", ]
      summary: "List all messages"

responses:
  500:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/Error'
