swagger: "2.0"
info:
  title: "DeepSpace Docs"
  description: >
    Docs de DeepSpace API.
  version: "1.0.0"
host: "${DB_HOST}:${PORT}"
schemes:
  - "http"
tags:
  - name: "auth"
    description: "Todo lo relacionado a autenticación"
  - name: "users"
    description: "Todo lo relacionado a users"
  - name: "chats"
    description: "Todo lo relacionado a chats"
  - name: "messages"
    description: "Todo lo relacionado a messages"

paths:
  /auth/login:
    post:
      tags: ["auth", ]
      summary: "Inicia sesión"
      description: "Inicia sesión con los datos proporcionados."
      parameters:
        - in: "body"
          name: "body"
          description: "El usuario que debe iniciar sesión"
          required: true
          schema:
            type: "object"
            properties:
              email:
                type: "string"
                format: "email"
              password:
                type: "string"
            required:
              - email
              - password
      responses:
        404:
          description: "No se encontró el usuario"
          schema:
            $ref: '#/definitions/Error'
        401:
          description: "Credenciales incorrectas"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Login exitoso"
          schema:
            type: "object"
            properties:
              token:
                type: "string"
              token_type:
                type: "string"
              expires_in:
                type: "integer"
              scope:
                type: "string"
            required:
              - token
              - token_type
              - expires_in
              - scope
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /auth/signup:
    post:
      tags: ["auth", ]
      summary: "Registra un nuevo usuario"
      description: "Registra un nuevo usuario con los datos proporcionados."
      parameters:
        - in: "body"
          name: "body"
          description: "El usuario que debe ser registrado"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              last_name:
                type: "string"
              password:
                type: "string"
              email:
                type: "string"
              phone:
                type: "string"
              profile_picture:
                type: "string"
              files:
                type: "array"
                items:
                  $ref: '#/definitions/File'
            required:
              - name
              - last_name
              - password
              - email
              - phone
              - profile_picture
              - files
      responses:
        400:
          description: "Ya existe un usuario con ese email"
          schema:
            $ref: '#/definitions/Error'
        201:
          description: "Usuario registrado correctamente."
          schema:
            $ref: "#/definitions/Success"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /users:
    get:
      tags: ["users", ]
      summary: "Recupera todos los usuarios"
      description: "Recupera todos los usuarios de la base de datos."
      responses:
        200:
          description: "Una lista de usuarios"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    delete:
      tags: ["users", ]
      summary: "Elimina un usuario"
      description: "Elimina un usuario con el id proporcionado."
      parameters:
        - in: "query"
          name: "id"
          required: true
          description: "ID del usuario"
          type: "integer"
          format: "int64"
      responses:
        404:
          description: "No se encontró el usuario"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Usuario eliminado correctamente."
          schema:
            $ref: "#/definitions/Success"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    post:
      tags: ["users", ]
      summary: "Crear un nuevo usuario"
      description: "Crea un nuevo usuario con los datos proporcionados."
      parameters:
        - in: "body"
          name: "body"
          description: "El usuario que debe ser creado"
          required: true
          schema:
            $ref: "#/definitions/UserEntity"
      responses:
        201:
          description: "Usuario creado correctamente."
          schema:
            $ref: "#/definitions/User"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /users/{id}:
    patch:
      tags: ["users", ]
      summary: "Edita un usuario"
      description: "Edita un usuario con el id proporcionado."
      parameters:
        - in: "query"
          name: "id"
          required: true
          description: "ID del usuario"
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "El usuario que debe ser editado"
          required: true
          schema:
            $ref: "#/definitions/UserEntity"
      responses:
        400:
          description: "Se requiere la id del usuario"
          schema:
            $ref: '#/definitions/Error'
        404:
          description: "No se encontró el usuario"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Usuario editado correctamente."
          schema:
            $ref: "#/definitions/Success"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /chats:
    get:
      tags: ["chats", ]
      summary: "Recupera los chats de un usuario"
      parameters:
      - in: "query"
        name: "userId"
        required: true
        description: "ID del usuario"
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Una lista de chats"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Chat"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    post:
      tags: ["chats", ]
      summary: "Crea un nuevo chat"
      description: "Crea un nuevo chat con los datos proporcionados."
      parameters:
        - in: "body"
          name: "body"
          description: "El chat que debe ser creado"
          required: true
          schema:
            $ref: "#/definitions/ChatEntity"
  /chats/{id}:
    get:
      tags: ["chats"]
      summary: "Recupera los mensajes de un chat"
      parameters:
        - in: "path"
          name: "id"
          required: true
          description: "ID del chat"
          type: "integer"
          format: "int64"
      responses:
        404:
          description: "No se encontraró el chat"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Una lista de mensajes de un chat"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/FullMessage"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /chats/dms/{id}:
    get:
      tags: ["chats"]
      summary: "Recupera la id del DM entre dos usuarios"
      parameters:
        - in: "path"
          name: "id"
          required: true
          description: "ID de algun usuario"
          type: "integer"
          format: "int64"
      responses:
        404:
          description: "No se encontraró el DM"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Una id de chat"
          schema:
            type: "integer"
            format: "int64"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /chats/details/{id}:
    get:
      tags: ["chats"]
      summary: "Recupera los detalles del chat (miembros, fecha creacion, etc)"
      parameters:
        - in: "path"
          name: "id"
          required: true
          description: "ID de algun Chat"
          type: "integer"
          format: "int64"
      responses:
        404:
          description: "No se encontraró el Chat"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Los detalles del chat"
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              imageUrl:
                type: "string"
                nullable: true
              createdAt:
                type: "string"
                format: "date-time"
              members:
                type: "array"
                items:
                  $ref: '#/definitions/Member'
              files:
                type: "array"
                items:
                  $ref: '#/definitions/MessageFile'
              urls:
                type: "array"
                items:
                  type: "string"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /messages:
    get:
        tags: ["messages", ]
        summary: "Obtiene todos los mensajes"
        description: "Obtiene todos los mensajes"
        responses:
          200:
            description: "La lista de mensajes"
            schema:
              type: "array"
              items:
                $ref: "#/definitions/Message"
          500:
            description: "Internal Server Error"
            schema:
              $ref: '#/definitions/Error'
    post:
      tags: ["messages", ]
      summary: "Crea un mensaje nuevo"
      description: "Crea un mensaje nuevo con los datos proporcionados."
      parameters:
        - in: "body"
          name: "body"
          description: "El mensaje que debe ser creado"
          required: true
          schema:
            $ref: "#/definitions/MessageEntity"
      responses:
        400:
          description: "Faltaron parametros. Se requiere idUser, idChat y message o files"
          schema:
            $ref: '#/definitions/Error'
        403:
          description: "No tienes permiso para enviar mensajes en este chat"
          schema:
            $ref: '#/definitions/Error'
        201:
          description: "Mensaje creado correctamente."
          schema:
            $ref: "#/definitions/FullMessage"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    delete:
      tags: ["messages", ]
      summary: "Elimina un mensaje"
      description: "Elimina un mensaje con el id proporcionado."
      parameters:
        - in: "query"
          name: "id"
          required: true
          description: "ID del mensaje"
          type: "integer"
          format: "int64"
      responses:
        404:
          description: "No se encontró el mensaje"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Mensaje eliminado correctamente."
          schema:
            $ref: "#/definitions/Success"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
    patch:
      tags: ["messages", ]
      summary: "Edita un mensaje"
      description: "Edita un mensaje con el id proporcionado."
      parameters:
        - in: "query"
          name: "id"
          required: true
          description: "ID del mensaje"
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "El mensaje que debe ser editado"
          required: true
          schema:
            $ref: "#/definitions/MessageUpdateEntity"
      responses:
        404:
          description: "No se encontró el mensaje"
          schema:
            $ref: '#/definitions/Error'
        200:
          description: "Mensaje editado correctamente."
          schema:
            $ref: "#/definitions/FullMessage"
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Error'
  /messages/{id}:
    get:
        tags: ["messages", ]
        summary: "Obtiene un mensaje"
        description: "Obtiene el mensaje con el id proporcionado."
        parameters:
          - in: "query"
            name: "id"
            required: true
            description: "ID del mensaje"
            type: "integer"
            format: "int64"
        responses:
          404:
            description: "No se encontró el mensaje"
            schema:
              $ref: '#/definitions/Error'
          200:
            description: "El mensaje"
            schema:
              $ref: "#/definitions/MessageEntity"
          500:
            description: "Internal Server Error"
            schema:
              $ref: '#/definitions/Error'
responses:
  500:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: "object"
    properties:
      error:
        type: "string"
  Success:
    type: "object"
    properties:
      message:
        type: "string"
  Chat:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      imageUrl:
        type: "string"
        nullable: true
      canSendMessage:
        type: "boolean"
      lastMessage:
        $ref: "#/definitions/Message"
      isDm: 
        type: "boolean"
  ChatEntity:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      image_url:
        type: "string"
        nullable: true
      mode:
        type: "string"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      lastName:
        type: "string"
      profilePictureUrl:
        type: "string"
  Member:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      lastName:
        type: "string"
      profilePictureUrl:
        type: "string"
      role:
        type: "string"
  UserEntity:
    type: "object"
    properties:
      name:
        type: "string"
      last_name:
        type: "string"
      password:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      profile_picture:
        type: "string"        
  FullMessage:
    type: "object"
    properties:
      id:
        type: "integer"
      idChat: 
        type: "integer"
      idUser:
        type: "integer"
      message:
        type: "string"
      lastEditDate: 
        type: "string"
        nullable: true
        format: "date-time"
      deletesAt: 
        type: "string"
        nullable: true
        format: "date-time"
      forwaded:
        type: "boolean"
      respondingTo:
        type: "integer"
        nullable: true
      time:
        type: "string"
        format: "date-time"
      user:
        $ref: "#/definitions/User"
      files:
        type: "array"
        items:
          $ref: "#/definitions/MessageFile"
  Message:
    type: "object"
    properties:
      message:
        type: "string"
      time:
        type: "string"
        format: "date-time"
  MessageEntity:
    type: "object"
    properties:
      idChat:
        type: "integer"
      idUser:
        type: "integer"
      message:
        type: "string"
      pinned:
        type: "boolean"
        default: false
      deletesAt:
        type: "string"
        format: "date-time"
        nullable: true
      forwaded:
        type: "boolean"
      respondingTo:
        type: "integer"
        nullable: true
      files:
        type: "array"
        items:
          $ref: "#/definitions/File"
  MessageFile:
    type: "object"
    properties:
      id:
        type: "integer"
      file_url:
        type: "string"
  File:
    type: "object"
    properties:
      name:
        type: "string"
      lastModified:
        type: "integer"
      lastModifiedDate:
        type: "string"
      webkitRelativePath:
        type: "string"
      size:
        type: "integer"
      type:
        type: "string"
    required:
      - name
      - lastModified
      - lastModifiedDate
      - webkitRelativePath
      - size
      - type
  MessageUpdateEntity:
    type: "object"
    properties:
      message:
        type: "string"
      pinned:
        type: "boolean"
        default: false
      deletesAt:
        type: "string"
        format: "date-time"
        nullable: true
